# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-08-13 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lufei', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.SmallIntegerField(choices=[(0, '付费'), (1, 'VIP专享'), (2, '学位课程'), (3, '免费课')], default=''),
        ),
    ]
