# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-08-14 06:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lufei', '0003_auto_20200814_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoutline',
            name='course_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outlines', to='lufei.CourseDetail'),
        ),
    ]
