# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-08-14 07:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lufei', '0004_auto_20200814_1402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseoutline',
            options={'ordering': ['order'], 'verbose_name_plural': '09. 课程大纲'},
        ),
        migrations.AlterField(
            model_name='courseoutline',
            name='course_detail',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outlines', to='lufei.CourseDetail'),
        ),
    ]
